# Generated by Django 4.2.3 on 2023-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField(choices=[(0, 'Tak'), (1, 'Nie'), (2, 'Jeszcze nie wiem')], default=2)),
                ('gender', models.IntegerField(choices=[(0, 'Chłopiec'), (1, 'Dziewczynka'), (2, 'Nie podano')], default=2)),
            ],
        ),
    ]
