# Generated by Django 4.2.3 on 2023-07-16 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('girl_name', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='names',
            name='status',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(0, 'Tak'), (1, 'Nie'), (2, 'Jeszcze nie wiem')])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girl_name.names')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='names',
            name='user',
            field=models.ManyToManyField(through='girl_name.Choice', to=settings.AUTH_USER_MODEL),
        ),
    ]
