# Generated by Django 4.2.3 on 2023-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girl_name', '0002_remove_names_status_choice_names_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_change_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
