# Generated by Django 4.2.3 on 2023-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='02c18084-1130-462d-813c-70dd159a07ac', max_length=64, unique=True),
        ),
    ]
